import Head from 'next/head'
import GlobalWrapper from '../components/GlobalWrapper/GlobalWrapper'
import Content from '../components/Content';
import Projects from '../components/Projects';

export default function Home() {
  return (
    <>
      <Head>
        <title>Technical test => Socreative Digital</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <GlobalWrapper>
          <Content title='About Us' numParagraphs={30} />
          <Content title='TEAM' numParagraphs={15} />
          <Projects />
          <Content title='Contact' numParagraphs={15} />
        </GlobalWrapper>
    </>
  )
}
